<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ../../../../static/models/hologram_projector.glb
Author: dasnymth (https://sketchfab.com/dasnymth)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hologram-projector-905823a25aa1457ba4087c09b0f312aa
Title: Hologram Projector
-->

<script>
  import { Group, MeshStandardMaterial } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('./models/hologram_projector.glb')


  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group scale={0.03}>
      <T.Mesh geometry={gltf.nodes.pTorus1_body_0.geometry} material={gltf.materials.body} />
      <T.Mesh geometry={gltf.nodes.pTorus1_gem_0.geometry} material={gltf.materials.material} />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
